# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch: # Allows the workflow to be manually triggered
        inputs:
            workflow: # The name of the workflow to trigger
                description: "The name of the workflow to trigger"
                required: true
                default: "Build"
            branch: # The branch to trigger the workflow on
                description: "The branch to trigger the workflow on"
                required: true
                default: "master"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.branch }}
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
