# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: On Push

on:
    push:
        branches: ["master"]
    workflow_call: # Allows the workflow to be manually triggered
jobs:
    build:
        uses: ./.github/workflows/build.yml
    test:
        uses: ./.github/workflows/test.yml
    updatepackage:
        needs:
            - build
            - test
        uses: ./.github/workflows/updatepackage.yml
