# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Unit Tests

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Test & generate code coverage
              run: dotnet test /p:AltCover=true /p:CopyLocalLockFileAssemblies=true /p:AltCoverCobertura=coverage.xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: renatodellosso/EnvDotNet
                  files: EnvDotNet/coverage.xml
            - name: Upload coverage reports to Deepsource
              uses: deepsourcelabs/test-coverage-action@master
              with:
                  key: csharp
                  coverage-file: EnvDotNet/coverage.xml
                  dsn: ${{ secrets.DEEPSOURCE_DSN }}
