name: Unit Tests

on:
    workflow_call: # Allows the workflow to be manually triggered

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Test and generate code coverage
              run: dotnet test -c Debug /p:AltCover=true /p:CopyLocalLockFileAssemblies=true /p:AltCoverCobertura=coverage.xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.1.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
            - name: Upload coverage reports to Deepsource
              uses: deepsourcelabs/test-coverage-action@master
              with:
                  key: csharp
                  coverage-file: coverage.xml
                  dsn: ${{ secrets.DEEPSOURCE_DSN }}
