# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Update Package

on:
    workflow_call: # Allows the workflow to be manually triggered
jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            configuration: Release
    update:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build (Release)
              run: dotnet build --no-restore -c Release
            - name: Pack
              run: dotnet pack -c Release
