# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Update Package

on:
    workflow_call: # Allows the workflow to be manually triggered
jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            configuration: Release
    update:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/checkout@v3
            - name: Update Package
              run: |
                  dotnet pack -c Release
                  dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
